# Generated by Django 4.2.7 on 2026-02-07 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('cyberschool', 'Cyberschool'), ('moov_money', 'Moov Money'), ('airtel_money', 'Airtel Money'), ('autre', 'Autre')], default='cyberschool', max_length=50)),
                ('statut', models.CharField(choices=[('SUCCES', 'Succès'), ('ERREUR', 'Erreur'), ('EN_ATTENTE', 'En attente')], default='SUCCES', max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('headers', models.JSONField(default=dict)),
                ('reference_transaction', models.CharField(blank=True, max_length=255, null=True)),
                ('code_paiement', models.CharField(blank=True, max_length=50, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('message_erreur', models.TextField(blank=True, null=True)),
                ('tentatives', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weblogs_recus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Webhook',
                'verbose_name_plural': 'Logs Webhooks',
                'ordering': ['-date_reception'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('date_creation_compte', models.DateTimeField(auto_now_add=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('nb_filtres_realises', models.IntegerField(default=0)),
                ('est_actif', models.BooleanField(default=True)),
                ('a_un_abonnement', models.BooleanField(default=False)),
                ('type_abonnement', models.CharField(choices=[('mensuel', 'Mensuel'), ('annuel', 'Annuel'), ('a_vie', 'À vie'), ('gratuit', 'Gratuit')], default='gratuit', max_length=20)),
                ('date_debut_abonnement', models.DateTimeField(blank=True, null=True)),
                ('date_fin_abonnement', models.DateTimeField(blank=True, null=True)),
                ('filtres_gratuits_utilises', models.IntegerField(default=0)),
                ('date_reset_filtres', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Utilisateur',
                'verbose_name_plural': 'Profils Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du produit (ex: Mensuel, Essai 7 jours)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description du produit')),
                ('type_abonnement', models.CharField(choices=[('mensuel', 'Mensuel'), ('annuel', 'Annuel'), ('a_vie', 'À vie'), ('essai', 'Essai gratuit'), ('custom', 'Personnalisé')], max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, help_text='Prix en devise', max_digits=10)),
                ('devise', models.CharField(default='XAF', help_text='Devise (XAF, EUR, USD...)', max_length=10)),
                ('duree_jours', models.IntegerField(blank=True, help_text='Durée en jours (null pour à vie)', null=True)),
                ('duree_heures', models.IntegerField(blank=True, help_text='Durée en heures (pour essais)', null=True)),
                ('url_moov_money', models.URLField(blank=True, help_text='URL de paiement Moov Money avec paramètres')),
                ('url_airtel_money', models.URLField(blank=True, help_text='URL de paiement Airtel Money avec paramètres')),
                ('est_actif', models.BooleanField(default=True, help_text='Produit visible sur le site')),
                ('ordre_affichage', models.IntegerField(default=0, help_text="Ordre d'affichage (plus petit = en premier)")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Produit d'abonnement",
                'verbose_name_plural': "Produits d'abonnements",
                'ordering': ['ordre_affichage', 'prix'],
                'indexes': [models.Index(fields=['type_abonnement'], name='gosen_subsc_type_ab_ee4050_idx'), models.Index(fields=['est_actif'], name='gosen_subsc_est_act_22da7a_idx'), models.Index(fields=['ordre_affichage'], name='gosen_subsc_ordre_a_1b9e6d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_abonnement', models.CharField(choices=[('mensuel', 'Mensuel'), ('annuel', 'Annuel'), ('a_vie', 'À vie')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(default='XAF', max_length=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('complete', 'Complété'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('reference_transaction', models.CharField(max_length=255, unique=True)),
                ('code_paiement', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='gosen.subscriptionproduct')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('webhook_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='gosen.webhooklog')),
            ],
            options={
                'verbose_name': 'Paiement abonnement',
                'verbose_name_plural': 'Paiements abonnements',
                'ordering': ['-date_creation'],
            },
        ),
    ]
