# Generated by Django 4.2.7 on 2026-01-29 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GosenUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil utilisateur Gosen',
                'verbose_name_plural': 'Profils utilisateurs Gosen',
            },
        ),
        migrations.CreateModel(
            name='FilterPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('config', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='gosen.gosenuserprofile')),
            ],
            options={
                'verbose_name': 'Préréglage de filtre',
                'verbose_name_plural': 'Préréglages de filtres',
            },
        ),
    ]
