# Generated by Django 4.2.7 on 2026-02-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gosen', '0002_devicefingerprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom de l'utilisateur", max_length=200)),
                ('email', models.EmailField(help_text='Email de contact', max_length=254)),
                ('type_demande', models.CharField(choices=[('filtre', 'Demande de filtre supplémentaire'), ('support', 'Support technique'), ('partenariat', 'Proposition de partenariat'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('message', models.TextField(help_text="Message de l'utilisateur")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_traite', models.BooleanField(default=False, help_text="Message traité par l'admin")),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du partenaire', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Logo du partenaire', null=True, upload_to='partners/')),
                ('lien', models.URLField(blank=True, help_text='Lien vers le site du partenaire')),
                ('description', models.TextField(blank=True, help_text='Description du partenaire')),
                ('ordre_affichage', models.IntegerField(default=0, help_text="Ordre d'affichage (plus petit = en premier)")),
                ('est_actif', models.BooleanField(default=True, help_text='Partenaire visible sur le site')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
    ]
