# Generated by Django 4.2.7 on 2026-02-01 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gosen', '0002_adminuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilterPreset',
        ),
        migrations.DeleteModel(
            name='GosenUserProfile',
        ),
    ]
