# Generated by Django 4.2.7 on 2026-02-01 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gosen', '0003_delete_filterpreset_delete_gosenuserprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
