# Generated by Django 4.2.7 on 2026-02-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gosen', '0003_contactmessage_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='nom',
            field=models.CharField(blank=True, default='', help_text='Nom du partenaire (optionnel)', max_length=200, null=True),
        ),
    ]
