# Generated by Django 4.2.7 on 2026-02-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gosen', '0004_partner_nom_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionproduct',
            name='logo_airtel_money',
            field=models.ImageField(blank=True, help_text='Logo Airtel Money', null=True, upload_to='payment_logos/'),
        ),
        migrations.AddField(
            model_name='subscriptionproduct',
            name='logo_moov_money',
            field=models.ImageField(blank=True, help_text='Logo Moov Money', null=True, upload_to='payment_logos/'),
        ),
    ]
