# Generated by Django 4.2.7 on 2026-02-18 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gosen', '0005_subscriptionproduct_logo_airtel_money_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionproduct',
            name='logo_airtel_money',
        ),
        migrations.RemoveField(
            model_name='subscriptionproduct',
            name='logo_moov_money',
        ),
        migrations.CreateModel(
            name='BacktestAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_partants', models.IntegerField(help_text='Nombre de partants')),
                ('taille_combinaison', models.IntegerField(help_text='Taille des combinaisons')),
                ('pronostics', models.JSONField(help_text='Groupes de pronostics saisis')),
                ('criteres_filtres', models.JSONField(help_text='Critères de filtrage utilisés')),
                ('arrivee', models.JSONField(help_text='Arrivée testée (liste de numéros)')),
                ('combinaisons_filtrees', models.JSONField(help_text='Combinaisons après filtrage')),
                ('combinaisons_trouvees', models.JSONField(help_text="Combinaisons contenant l'arrivée")),
                ('nombre_trouvees', models.IntegerField(default=0, help_text='Nombre de combinaisons trouvées')),
                ('rapport', models.TextField(help_text='Rapport complet du backtest')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('nom', models.CharField(blank=True, default='', help_text="Nom personnalisé de l'analyse", max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analyse de Backtest',
                'verbose_name_plural': 'Analyses de Backtest',
                'ordering': ['-date_creation'],
            },
        ),
    ]
