# Generated by Django 4.2.7 on 2026-02-20 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gosen', '0006_remove_subscriptionproduct_logo_airtel_money_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('date_connexion', models.DateTimeField(auto_now_add=True)),
                ('derniere_activite', models.DateTimeField(auto_now=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Utilisateur',
                'verbose_name_plural': 'Sessions Utilisateurs',
                'ordering': ['-derniere_activite'],
                'indexes': [models.Index(fields=['session_key'], name='gosen_users_session_dd8b1c_idx'), models.Index(fields=['est_actif'], name='gosen_users_est_act_571efc_idx'), models.Index(fields=['-derniere_activite'], name='gosen_users_dernier_3d28b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('connexion', 'Connexion'), ('deconnexion', 'Déconnexion'), ('inscription', 'Inscription'), ('filtre_realise', 'Filtre réalisé'), ('abonnement_souscrit', 'Abonnement souscrit'), ('paiement_recu', 'Paiement reçu'), ('backtest_sauvegarde', 'Backtest sauvegardé'), ('message_contact', 'Message de contact'), ('erreur', 'Erreur système'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('donnees', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'activité",
                'verbose_name_plural': "Logs d'activité",
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['-date_creation'], name='gosen_activ_date_cr_2aa15d_idx'), models.Index(fields=['type_action'], name='gosen_activ_type_ac_4eee0c_idx'), models.Index(fields=['user'], name='gosen_activ_user_id_a2ad3d_idx')],
            },
        ),
    ]
