# Generated by Django 4.2.7 on 2026-02-01 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gosen', '0007_remove_unused_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('cyberschool', 'Cyberschool'), ('moov_money', 'Moov Money'), ('airtel_money', 'Airtel Money'), ('autre', 'Autre')], default='cyberschool', max_length=50)),
                ('statut', models.CharField(choices=[('SUCCES', 'Succès'), ('ERREUR', 'Erreur'), ('EN_ATTENTE', 'En attente')], default='SUCCES', max_length=20)),
                ('payload', models.JSONField(default=dict, help_text='Données brutes reçues')),
                ('headers', models.JSONField(default=dict, help_text='En-têtes HTTP reçus')),
                ('reference_transaction', models.CharField(blank=True, help_text='Référence de la transaction', max_length=255, null=True)),
                ('code_paiement', models.CharField(blank=True, help_text='Code de paiement', max_length=50, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, help_text='Montant payé', max_digits=10, null=True)),
                ('telephone', models.CharField(blank=True, help_text='Numéro de téléphone', max_length=50, null=True)),
                ('date_reception', models.DateTimeField(auto_now_add=True, help_text='Date de réception du webhook')),
                ('date_traitement', models.DateTimeField(blank=True, help_text='Date de traitement', null=True)),
                ('message_erreur', models.TextField(blank=True, help_text="Message d'erreur si échec", null=True)),
                ('tentatives', models.IntegerField(default=0, help_text='Nombre de tentatives de traitement')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="IP de l'expéditeur", null=True)),
                ('user_agent', models.TextField(blank=True, help_text="User Agent de l'expéditeur", null=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weblogs_recus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Webhook',
                'verbose_name_plural': 'Logs Webhooks',
                'ordering': ['-date_reception'],
                'indexes': [models.Index(fields=['reference_transaction'], name='gosen_webho_referen_1e308c_idx'), models.Index(fields=['statut'], name='gosen_webho_statut_7124c1_idx'), models.Index(fields=['source'], name='gosen_webho_source_fc63d1_idx'), models.Index(fields=['-date_reception'], name='gosen_webho_date_re_3ea950_idx')],
            },
        ),
    ]
