# Generated by Django 4.2.7 on 2026-02-20 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gosen', '0007_usersession_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=255)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.TextField(blank=True)),
                ('premiere_visite', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('derniere_activite', models.DateTimeField(auto_now=True, db_index=True)),
                ('est_actif', models.BooleanField(db_index=True, default=True)),
                ('nombre_visites', models.IntegerField(default=1)),
                ('nombre_pages_vues', models.IntegerField(default=1)),
                ('pages_vues_session', models.JSONField(blank=True, default=list)),
                ('pays', models.CharField(blank=True, max_length=100, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tracking Appareil',
                'verbose_name_plural': 'Tracking Appareils',
                'ordering': ['-derniere_activite'],
                'indexes': [models.Index(fields=['fingerprint'], name='gosen_devic_fingerp_37493f_idx'), models.Index(fields=['ip_address'], name='gosen_devic_ip_addr_ef5850_idx'), models.Index(fields=['-derniere_activite'], name='gosen_devic_dernier_698be9_idx'), models.Index(fields=['est_actif'], name='gosen_devic_est_act_045c03_idx')],
            },
        ),
    ]
