# Generated by Django 4.2.7 on 2026-02-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gosen', '0008_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Frais de transaction', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant total (incluant les frais)', max_digits=10, null=True),
        ),
    ]
