# Generated by Django 4.2.7 on 2026-02-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gosen', '0008_devicetracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Numéro WhatsApp avec indicatif', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(blank=True, help_text='Email de contact', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='type_demande',
            field=models.CharField(choices=[('don', 'Don'), ('partenariat', 'Partenariat'), ('acces_gratuit', 'Accès gratuit'), ('support', 'Support technique'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
    ]
