# Generated by Django 4.2.7 on 2026-02-03 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gosen', '0009_webhooklog_fees_webhooklog_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_abonnement', models.CharField(choices=[('mensuel', 'Mensuel'), ('annuel', 'Annuel'), ('a_vie', 'À vie')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(default='XAF', max_length=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('complete', 'Complété'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('reference_transaction', models.CharField(max_length=255, unique=True)),
                ('code_paiement', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Paiement abonnement',
                'verbose_name_plural': 'Paiements abonnements',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('date_creation_compte', models.DateTimeField(auto_now_add=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('nb_filtres_realises', models.IntegerField(default=0)),
                ('est_actif', models.BooleanField(default=True)),
                ('a_un_abonnement', models.BooleanField(default=False)),
                ('type_abonnement', models.CharField(choices=[('mensuel', 'Mensuel'), ('annuel', 'Annuel'), ('a_vie', 'À vie'), ('gratuit', 'Gratuit')], default='gratuit', max_length=20)),
                ('date_debut_abonnement', models.DateTimeField(blank=True, null=True)),
                ('date_fin_abonnement', models.DateTimeField(blank=True, null=True)),
                ('filtres_gratuits_utilises', models.IntegerField(default=0)),
                ('date_reset_filtres', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Profil Utilisateur',
                'verbose_name_plural': 'Profils Utilisateurs',
            },
        ),
        migrations.RemoveIndex(
            model_name='webhooklog',
            name='gosen_webho_referen_1e308c_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhooklog',
            name='gosen_webho_statut_7124c1_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhooklog',
            name='gosen_webho_source_fc63d1_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhooklog',
            name='gosen_webho_date_re_3ea950_idx',
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='code_paiement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='date_reception',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='date_traitement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='headers',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='message_erreur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='payload',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='reference_transaction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='tentatives',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='webhook_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='gosen.webhooklog'),
        ),
    ]
