# Generated by Django 4.2.7 on 2026-02-23 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gosen', '0009_contactmessage_whatsapp_alter_contactmessage_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedResultConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom de la sauvegarde', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('num_partants', models.IntegerField(help_text='Nombre de partants')),
                ('taille_combinaison', models.IntegerField(help_text='Taille des combinaisons')),
                ('pronostics_text', models.TextField(help_text='Texte brut des pronostics (textarea)')),
                ('criteres_filtres', models.JSONField(default=dict, help_text='Critères des filtres utilisés')),
                ('reunion', models.CharField(blank=True, help_text='Réunion (ex: R1)', max_length=50, null=True)),
                ('date_course', models.DateField(blank=True, help_text='Date de la course', null=True)),
                ('arrivee', models.JSONField(blank=True, help_text='Arrivée [1,2,3,4,5,6,7,8]', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration sauvegardée',
                'verbose_name_plural': 'Configurations sauvegardées',
                'ordering': ['-created_at'],
            },
        ),
    ]
