# Generated by Django 4.2.7 on 2026-03-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gosen', '0010_savedresultconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='SauvegardeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('num_partants', models.IntegerField()),
                ('taille_combinaison', models.IntegerField()),
                ('pronostics', models.JSONField(default=dict)),
                ('arrivee', models.JSONField(blank=True, default=list, null=True)),
                ('combinaisons_filtrees', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'ordering': ['-date_modification'],
            },
        ),
        migrations.DeleteModel(
            name='SavedResultConfig',
        ),
    ]
