# Generated by Django 4.2.7 on 2026-03-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gosen', '0011_sauvegardeconfiguration_delete_savedresultconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestanalysis',
            name='date_course',
            field=models.DateField(blank=True, help_text='Date de la course (optionnel)', null=True),
        ),
    ]
