# Generated by Django 6.0 on 2025-12-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educalims_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, help_text="ID unique de l'utilisateur Telegram", unique=True)),
                ('first_name', models.CharField(blank=True, help_text='Prénom', max_length=100)),
                ('last_name', models.CharField(blank=True, help_text='Nom', max_length=100)),
                ('username', models.CharField(blank=True, help_text="Nom d'utilisateur Telegram (@username)", max_length=100, null=True)),
                ('language_code', models.CharField(blank=True, help_text='Code langue (ex: fr, en)', max_length=10)),
                ('is_premium', models.BooleanField(default=False, help_text='Compte Telegram Premium')),
                ('is_bot', models.BooleanField(default=False, help_text='Est un bot')),
                ('photo_url', models.URLField(blank=True, help_text='URL de la photo de profil')),
                ('raw_data', models.JSONField(blank=True, help_text='Données brutes Telegram', null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True, help_text='Première connexion')),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Dernière connexion')),
                ('connection_count', models.PositiveIntegerField(default=1, help_text='Nombre de connexions')),
                ('is_active', models.BooleanField(default=True, help_text='Utilisateur actif')),
            ],
            options={
                'verbose_name': 'Utilisateur Telegram',
                'verbose_name_plural': 'Utilisateurs Telegram',
                'ordering': ['-last_seen'],
            },
        ),
    ]
