# Generated by Django 6.0 on 2025-12-23 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educalims_app', '0002_telegramuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='couleur',
            field=models.CharField(default='#3498db', help_text='Code couleur HEX', max_length=7),
        ),
        migrations.AddField(
            model_name='discipline',
            name='icone',
            field=models.CharField(blank=True, help_text="Classe d'icône Bootstrap (ex: bi-calculator)", max_length=50),
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre de la séance', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description de la séance')),
                ('date_heure', models.DateTimeField(help_text='Date et heure de la séance')),
                ('duree_minutes', models.PositiveIntegerField(default=60, help_text='Durée en minutes')),
                ('places_max', models.PositiveIntegerField(default=50, help_text='Nombre de places maximum')),
                ('places_prises', models.PositiveIntegerField(default=0, help_text='Nombre de places réservées')),
                ('lien_meet', models.URLField(blank=True, help_text='Lien Google Meet/Zoom')),
                ('est_active', models.BooleanField(default=True, help_text='Séance active')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='educalims_app.discipline')),
            ],
            options={
                'verbose_name': 'Séance',
                'verbose_name_plural': 'Séances',
                'ordering': ['date_heure', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_abonnement', models.CharField(choices=[('ESSENTIEL', 'Accès Essentiel'), ('PROF_UNIQUE', 'Accès Prof - Séance Unique'), ('PROF_INTEGRAL', 'Accès Prof - Intégral')], help_text="Type d'abonnement", max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de paiement'), ('ACTIF', 'Actif'), ('ANNULE', 'Annulé'), ('EXPIRE', 'Expiré')], default='EN_ATTENTE', help_text="Statut de l'abonnement", max_length=20)),
                ('date_debut', models.DateTimeField(help_text="Date de début de l'abonnement")),
                ('date_fin', models.DateTimeField(help_text="Date de fin de l'abonnement")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('montant_paye', models.PositiveIntegerField(default=0, help_text='Montant payé en FCFA')),
                ('reference_transaction', models.CharField(blank=True, help_text='Référence de la transaction', max_length=100)),
                ('discipline', models.ForeignKey(help_text='Discipline associée', on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='educalims_app.discipline')),
                ('utilisateur', models.ForeignKey(help_text='Utilisateur Telegram', on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='educalims_app.telegramuser')),
                ('seance', models.ForeignKey(blank=True, help_text='Séance spécifique (pour abonnement UNIQUE)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonnements_unique', to='educalims_app.seance')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-date_creation'],
                'unique_together': {('utilisateur', 'discipline', 'type_abonnement', 'seance')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, help_text='Référence unique de la transaction', max_length=100, unique=True)),
                ('montant', models.PositiveIntegerField(help_text='Montant de la transaction en FCFA')),
                ('devise', models.CharField(default='XAF', help_text='Code devise (XAF, EUR, etc.)', max_length=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('SUCCES', 'Succès'), ('ECHEC', 'Échec'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', help_text='Statut de la transaction', max_length=20)),
                ('fournisseur', models.CharField(blank=True, help_text='Nom du prestataire de paiement', max_length=50)),
                ('fournisseur_transaction_id', models.CharField(blank=True, help_text='ID de transaction chez le prestataire', max_length=100)),
                ('donnees_brutes', models.JSONField(blank=True, help_text='Données brutes du prestataire', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création')),
                ('date_validation', models.DateTimeField(blank=True, help_text='Date de validation du paiement', null=True)),
                ('abonnements', models.ManyToManyField(blank=True, help_text='Abonnements créés par cette transaction', related_name='transactions', to='educalims_app.abonnement')),
                ('utilisateur', models.ForeignKey(help_text='Utilisateur Telegram', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='educalims_app.telegramuser')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date_creation'],
            },
        ),
    ]
