# Generated by Django 6.0 on 2025-12-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educalims_app', '0003_discipline_couleur_discipline_icone_seance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='type_abonnement',
            field=models.CharField(choices=[('ESSENTIEL', 'Accès Essentiel'), ('SEANCE_UNIQUE', 'Séance Unique'), ('SEANCE_INTEGRAL', 'séance intégrale')], help_text="Type d'abonnement", max_length=20),
        ),
    ]
