# Generated by Django 6.0 on 2025-12-23 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educalims_app', '0004_alter_abonnement_type_abonnement'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='abonnement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='niveau',
            field=models.ForeignKey(help_text='Niveau associé', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='educalims_app.niveau'),
        ),
        migrations.AlterUniqueTogether(
            name='abonnement',
            unique_together={('utilisateur', 'discipline', 'niveau', 'type_abonnement', 'seance')},
        ),
    ]
