# Generated by Django 5.1.15 on 2026-01-23 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du scénario')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('n_partants', models.IntegerField(verbose_name='Nombre de partants')),
                ('k_taille', models.IntegerField(verbose_name='Taille de combinaison')),
                ('groups', models.JSONField(default=list, verbose_name='Groupes de pronostics')),
                ('filters', models.JSONField(default=dict, verbose_name='Filtres appliqués')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Favori')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public')),
                ('usage_count', models.IntegerField(default=0, verbose_name="Nombre d'utilisations")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scénario',
                'verbose_name_plural': 'Scénarios',
                'ordering': ['-is_favorite', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#009E60', max_length=7)),
                ('scenarios', models.ManyToManyField(related_name='tags', to='hippie.scenario')),
            ],
        ),
    ]
