# Generated by Django 5.1.15 on 2026-01-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hippie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='arrivee',
            field=models.JSONField(blank=True, null=True, verbose_name='Arrivée de la course'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='date_course',
            field=models.DateField(blank=True, null=True, verbose_name='Date de la course'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='nb_combinaisons_restantes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de combinaisons restantes'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='nom_course',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom de la course'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='pronostics_text',
            field=models.TextField(blank=True, verbose_name='Texte des pronostics'),
        ),
    ]
