# Generated by Django 6.0 on 2026-01-25 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hippie', '0002_scenario_arrivee_scenario_date_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('produit_id', models.CharField(help_text='ID Cyberschool', max_length=100, unique=True)),
                ('prix', models.PositiveIntegerField(help_text='Prix en FCFA')),
                ('url_paiement', models.URLField(help_text='URL de base Cyberschool')),
                ('duree_jours', models.PositiveIntegerField(default=1, help_text='Durée en jours')),
                ('description', models.TextField(blank=True)),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Produit d'abonnement",
                'verbose_name_plural': "Produits d'abonnement",
                'ordering': ['-est_actif', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='SessionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Utilisateur de session',
                'verbose_name_plural': 'Utilisateurs de session',
                'ordering': ['-last_active'],
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACTIF', 'Actif'), ('EXPIRE', 'Expiré')], default='EN_ATTENTE', max_length=20)),
                ('merchant_reference_id', models.CharField(max_length=200, unique=True)),
                ('montant_paye', models.PositiveIntegerField(blank=True, null=True)),
                ('methode_paiement', models.CharField(blank=True, max_length=20)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='hippie.produitabonnement')),
                ('session_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='hippie.sessionuser')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_reference_id', models.CharField(max_length=255)),
                ('code', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('operator', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('activation_succes', models.BooleanField(default=False)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('abonnement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='hippie.abonnement')),
            ],
            options={
                'verbose_name': 'Journal Webhook',
                'verbose_name_plural': 'Journaux Webhooks',
                'ordering': ['-created_at'],
            },
        ),
    ]
