# Generated by Django 5.1.15 on 2026-01-15 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educalims', '0003_remove_abonnement_reference_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fichier',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='unite',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_reference_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Référence marchand')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='Code de réponse')),
                ('status', models.CharField(choices=[('SUCCESS', 'Succès'), ('FAILED', 'Échec'), ('PENDING', 'En attente')], max_length=20, verbose_name='Statut')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant')),
                ('operator', models.CharField(blank=True, max_length=50, null=True, verbose_name='Opérateur')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Transaction')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone')),
                ('activation_succes', models.BooleanField(default=False, verbose_name='Activation réussie')),
                ('telegram_notification_sent', models.BooleanField(default=True, verbose_name='Notif Telegram envoyée')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Données brutes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de réception')),
                ('abonnement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='educalims.abonnement', verbose_name='Abonnement')),
            ],
            options={
                'verbose_name': 'Journal Webhook',
                'verbose_name_plural': 'Journaux Webhooks',
                'ordering': ['-created_at'],
            },
        ),
    ]
