# Generated by Django 6.0.1 on 2026-01-18 11:29

import educalims.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educalims', '0005_alter_abonnement_id_alter_cycle_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='duree_jours',
        ),
        migrations.AddField(
            model_name='produit',
            name='date_expiration',
            field=models.DateField(default=educalims.models.get_default_expiration_date, help_text="Date d'expiration de l'abonnement (31 août par défaut)"),
        ),
    ]
