# Generated by Django 6.0.1 on 2026-01-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educalims', '0006_remove_produit_duree_jours_produit_date_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='device_id',
            field=models.CharField(blank=True, help_text='Identifiant unique de l appareil autorise', max_length=255, null=True, unique=True),
        ),
    ]
