# Generated by Django 6.0.1 on 2026-01-13 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cycle',
                'verbose_name_plural': 'Cycles',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('couleur', models.CharField(default='#667eea', help_text='Code hexadécimal de la couleur', max_length=7)),
                ('icone', models.CharField(blank=True, help_text="Nom de l'icône (FontAwesome, etc.)", max_length=50)),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cycles', models.ManyToManyField(blank=True, related_name='disciplines', to='educalims.cycle')),
            ],
            options={
                'verbose_name': 'Discipline',
                'verbose_name_plural': 'Disciplines',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('specialite', models.CharField(choices=[('L', 'Littéraire'), ('S', 'Scientifique'), ('T', 'Technologique'), ('P', 'Professionnelle'), ('A', 'Autre')], default='A', help_text='Spécialité du niveau', max_length=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
                ('est_niveau_enfant', models.BooleanField(default=False, help_text='True si ce niveau a un niveau parent (ex: Terminale C)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='educalims.cycle')),
                ('disciplines', models.ManyToManyField(blank=True, related_name='niveaux', to='educalims.discipline')),
                ('niveau_parent', models.ForeignKey(blank=True, help_text='Niveau parent (ex: Terminale pour Terminale C)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='niveaux_enfants', to='educalims.niveau')),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_unite', models.CharField(choices=[('C', 'Chapitre'), ('P', 'Partie'), ('S', 'Section'), ('L', 'Leçon'), ('T', 'Thème')], default='C', help_text="Type de l'unité", max_length=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unites', to='educalims.discipline')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unites', to='educalims.niveau')),
                ('unite_parent', models.ForeignKey(blank=True, help_text='Unité parente pour créer une hiérarchie', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unites_enfants', to='educalims.unite')),
            ],
            options={
                'verbose_name': 'Unité',
                'verbose_name_plural': 'Unités',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_fichier', models.CharField(choices=[('TXT', 'Texte'), ('PDF', 'PDF'), ('VID', 'Vidéo'), ('LNK', 'Lien'), ('IMG', 'Image'), ('DOC', 'Document')], default='PDF', help_text='Type du fichier', max_length=3)),
                ('fichier', models.FileField(blank=True, help_text='Fichier uploadé (pour PDF, images, etc.)', null=True, upload_to='fichiers/%Y/%m/')),
                ('contenu_texte', models.TextField(blank=True, help_text='Contenu texte directement', null=True)),
                ('url_lien', models.URLField(blank=True, help_text='URL externe (pour les liens)', null=True)),
                ('duree', models.PositiveIntegerField(blank=True, help_text='Durée en secondes (pour les vidéos)', null=True)),
                ('taille', models.PositiveIntegerField(blank=True, help_text='Taille du fichier en octets', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('telechargements', models.PositiveIntegerField(default=0, help_text='Nombre de téléchargements')),
                ('est_actif', models.BooleanField(default=True, help_text='Fichier visible/accessible')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='educalims.unite')),
            ],
            options={
                'verbose_name': 'Fichier',
                'verbose_name_plural': 'Fichiers',
                'ordering': ['-date_creation', 'nom'],
            },
        ),
        migrations.AddConstraint(
            model_name='niveau',
            constraint=models.UniqueConstraint(condition=models.Q(('niveau_parent__isnull', False)), fields=('nom', 'niveau_parent'), name='unique_niveau_enfant_par_parent'),
        ),
    ]
