# Generated by Django 6.0.1 on 2026-01-13 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educalims', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.PositiveIntegerField(help_text='Prix en FCFA')),
                ('airtel_money_url', models.URLField(blank=True, help_text='URL de paiement Airtel Money', null=True)),
                ('moov_money_url', models.URLField(blank=True, help_text='URL de paiement Moov Money', null=True)),
                ('duree_jours', models.PositiveIntegerField(default=30, help_text="Durée de l'abonnement en jours")),
                ('est_actif', models.BooleanField(default=True, help_text='Produit disponible à la vente')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-date_creation', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de paiement'), ('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('ANNULE', 'Annulé'), ('ECHOUE', 'Échec du paiement')], default='EN_ATTENTE', help_text="Statut de l'abonnement", max_length=20)),
                ('reference_transaction', models.CharField(blank=True, help_text='Référence unique de la transaction', max_length=200, null=True, unique=True)),
                ('code_paiement', models.CharField(blank=True, help_text='Code de réponse du paiement (ex: 200 pour succès)', max_length=10, null=True)),
                ('methode_paiement', models.CharField(blank=True, help_text='Méthode de paiement utilisée (Airtel/Moov)', max_length=20, null=True)),
                ('montant_paye', models.PositiveIntegerField(blank=True, help_text='Montant réellement payé', null=True)),
                ('date_debut', models.DateTimeField(blank=True, help_text="Date de début de l'abonnement", null=True)),
                ('date_fin', models.DateTimeField(blank=True, help_text="Date de fin de l'abonnement", null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='educalims.niveau')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='educalims.produit')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-date_creation', '-date_debut'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('statut', 'ACTIF')), fields=('user', 'niveau', 'statut'), name='unique_abonnement_actif_par_user_niveau')],
            },
        ),
    ]
