# Generated by Django 6.0.1 on 2026-01-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educalims', '0002_produit_abonnement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonnement',
            name='reference_transaction',
        ),
        migrations.AddField(
            model_name='abonnement',
            name='merchant_reference_id',
            field=models.CharField(blank=True, help_text='Reference marchand envoyee a Cyberschool et renvoyee dans le callback', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='reference_interne',
            field=models.CharField(blank=True, help_text='Notre reference interne unique de la transaction', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='code_paiement',
            field=models.CharField(blank=True, help_text='Code de reponse du paiement (ex: 200 pour succes)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='date_debut',
            field=models.DateTimeField(blank=True, help_text="Date de debut de l'abonnement", null=True),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='methode_paiement',
            field=models.CharField(blank=True, help_text='Methode de paiement utilisee (Airtel/Moov)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='montant_paye',
            field=models.PositiveIntegerField(blank=True, help_text='Montant reellement paye', null=True),
        ),
    ]
