# Generated by Django 5.2.8 on 2025-11-08 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('cycle', models.CharField(choices=[('College', 'Collège'), ('Lycee', 'Lycée')], max_length=20)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='educalims.discipline')),
            ],
        ),
        migrations.CreateModel(
            name='UniteEnseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_unite', models.CharField(choices=[('Leçon', 'Leçon'), ('Chapitre', 'Chapitre')], max_length=10)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unites', to='educalims.niveau')),
            ],
        ),
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_fichier', models.CharField(choices=[('Fiche', 'Fiche'), ('Sujet', 'Sujet'), ('CahierType', 'Cahier Type')], max_length=20)),
                ('fichier', models.FileField(upload_to='contenus/')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='educalims.uniteenseignement')),
            ],
        ),
    ]
