# Generated by Django 5.2.8 on 2025-11-08 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educalims', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='niveau',
            name='discipline',
        ),
        migrations.AlterField(
            model_name='discipline',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Contenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_contenu', models.CharField(choices=[('Fiche', 'Fiche'), ('Sujet', 'Sujet'), ('CahierType', 'Cahier Type')], max_length=20)),
                ('fichier', models.FileField(upload_to='contenus/')),
                ('unites', models.ManyToManyField(related_name='contenus', to='educalims.uniteenseignement')),
            ],
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='educalims.discipline')),
            ],
        ),
        migrations.AlterField(
            model_name='niveau',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='educalims.cycle'),
        ),
        migrations.DeleteModel(
            name='Fichier',
        ),
    ]
