# Generated by Django 5.2.8 on 2025-11-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educalims', '0002_remove_niveau_discipline_alter_discipline_nom_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uniteenseignement',
            options={'ordering': ['niveau__cycle__discipline__nom', 'niveau__cycle__nom', 'niveau__nom', 'titre']},
        ),
        migrations.AddField(
            model_name='uniteenseignement',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='unites_enseignement/'),
        ),
        migrations.DeleteModel(
            name='Contenu',
        ),
    ]
