# Generated by Django 5.2.8 on 2025-11-09 21:52

from django.db import migrations

def insert_lecons_sixieme(apps, schema_editor):
    # Importer les modèles via apps pour éviter les imports directs
    Discipline = apps.get_model('educalims', 'Discipline')
    Cycle = apps.get_model('educalims', 'Cycle')
    Niveau = apps.get_model('educalims', 'Niveau')
    UniteEnseignement = apps.get_model('educalims', 'UniteEnseignement')

    # Récupérer ou créer la discipline SVT
    svt_discipline, _ = Discipline.objects.get_or_create(
        nom='SVT',
        defaults={'nom': 'SVT'}
    )

    # Récupérer ou créer le cycle Collège
    college_cycle, _ = Cycle.objects.get_or_create(
        nom='Collège',
        defaults={'nom': 'Collège', 'discipline': svt_discipline}
    )

    # Récupérer ou créer le niveau 6ème
    sixieme_niveau, _ = Niveau.objects.get_or_create(
        nom='6ème',
        defaults={'nom': '6ème', 'cycle': college_cycle}
    )

    # Données des leçons pour la 6ème
    lecons_sixieme = [
        # Chapitre 1 : Environnement et répartition des êtres vivants
        {
            'titre': 'Chapitre 1 : Environnement et répartition des êtres vivants',
            'type_unite': 'Chapitre',
            'niveau': sixieme_niveau
        },
        {
            'titre': 'Leçon 1 : Les domaines d\'étude de la géologie (Présentation de la géologie)',
            'type_unite': 'Leçon',
            'niveau': sixieme_niveau
        },
        {
            'titre': 'Leçon 2 : Les composantes de l\'environnement',
            'type_unite': 'Leçon',
            'niveau': sixieme_niveau
        }
    ]

    # Insérer les leçons
    for lecon_data in lecons_sixieme:
        UniteEnseignement.objects.get_or_create(
            titre=lecon_data['titre'],
            type_unite=lecon_data['type_unite'],
            niveau=lecon_data['niveau'],
            defaults={'titre': lecon_data['titre']}
        )

def reverse_insert_lecons_sixieme(apps, schema_editor):
    # Code pour annuler l'insertion (supprimer les leçons insérées)
    UniteEnseignement = apps.get_model('educalims', 'UniteEnseignement')

    # Supprimer les leçons spécifiques qui ont été insérées
    titres_a_supprimer = [
        'Chapitre 1 : Environnement et répartition des êtres vivants',
        'Leçon 1 : Les domaines d\'étude de la géologie (Présentation de la géologie)',
        'Leçon 2 : Les composantes de l\'environnement'
    ]

    UniteEnseignement.objects.filter(titre__in=titres_a_supprimer).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('educalims', '0003_alter_uniteenseignement_options_and_more'),
    ]

    operations = [
        migrations.RunPython(insert_lecons_sixieme, reverse_insert_lecons_sixieme)
    ]
