# Generated by Django 5.2.8 on 2025-11-10 05:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('educalims', '0004_insert_lecons_sixieme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('numero', models.PositiveIntegerField(help_text="Numéro d'ordre du palier dans le niveau")),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paliers', to='educalims.niveau')),
            ],
            options={
                'ordering': ['niveau', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('numero', models.PositiveIntegerField(help_text="Numéro d'ordre du chapitre dans le palier")),
                ('palier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='educalims.palier')),
            ],
            options={
                'ordering': ['palier', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('numero', models.PositiveIntegerField(help_text="Numéro d'ordre de la leçon dans le chapitre")),
                ('description', models.TextField(blank=True, help_text='Description courte de la leçon')),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='educalims.chapitre')),
            ],
            options={
                'ordering': ['chapitre', 'numero'],
            },
        ),
        migrations.AlterModelOptions(
            name='uniteenseignement',
            options={'ordering': ['niveau__cycle__discipline__nom', 'niveau__cycle__nom', 'niveau__nom', 'titre']},
        ),
        migrations.RemoveField(
            model_name='uniteenseignement',
            name='type_unite',
        ),
        migrations.AddField(
            model_name='uniteenseignement',
            name='description',
            field=models.TextField(blank=True, help_text='Description de l\'unité d\'enseignement'),
        ),
        migrations.AddField(
            model_name='uniteenseignement',
            name='lecons',
            field=models.ManyToManyField(blank=True, help_text='Sélectionnez une ou plusieurs leçons à associer', related_name='unites_enseignement', to='educalims.lecon'),
        ),
        migrations.AddField(
            model_name='uniteenseignement',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uniteenseignement',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
