# Generated by Django 5.2.8 on 2025-11-10 19:13

from django.db import migrations, models
import django.db.models.deletion


def migrate_niveau_discipline(apps, schema_editor):
    """
    Migration des données pour assigner une discipline à chaque niveau
    basée sur l'ancienne relation cycle->discipline
    """
    Niveau = apps.get_model('educalims', 'Niveau')
    Cycle = apps.get_model('educalims', 'Cycle')
    
    # Récupérer tous les niveaux sans discipline
    niveaux_sans_discipline = Niveau.objects.filter(discipline__isnull=True)
    
    for niveau in niveaux_sans_discipline:
        # Essayer de trouver une discipline existante
        # Si aucune discipline n'existe, créer une discipline par défaut
        discipline, created = apps.get_model('educalims', 'Discipline').objects.get_or_create(
            nom="Mathématiques",
            defaults={'description': 'Discipline par défaut pour la migration'}
        )
        
        niveau.discipline = discipline
        niveau.save()


def reverse_migrate_niveau_discipline(apps, schema_editor):
    """
    Fonction inverse pour la migration
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('educalims', '0005_add_palier_chapitre_lecon'),
    ]

    operations = [
        # 1. Ajouter les champs description aux modèles existants
        migrations.AddField(
            model_name='discipline',
            name='description',
            field=models.TextField(blank=True, help_text='Description de la discipline'),
        ),
        
        migrations.AddField(
            model_name='cycle',
            name='description',
            field=models.TextField(blank=True, help_text='Description du cycle'),
        ),
        
        migrations.AddField(
            model_name='niveau',
            name='description',
            field=models.TextField(blank=True, help_text='Description du niveau'),
        ),
        
        migrations.AddField(
            model_name='palier',
            name='description',
            field=models.TextField(blank=True, help_text='Description du palier'),
        ),
        
        # 2. Créer le modèle Partie
        migrations.CreateModel(
            name='Partie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description de la partie')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='educalims.niveau')),
            ],
            options={
                'ordering': ['niveau', 'titre'],
            },
        ),
        
        # 3. Ajouter le champ discipline au modèle Niveau (nullable)
        migrations.AddField(
            model_name='niveau',
            name='discipline',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='niveaux', 
                to='educalims.discipline'
            ),
        ),
        
        # 4. Migration des données pour assigner une discipline à chaque niveau
        migrations.RunPython(migrate_niveau_discipline, reverse_migrate_niveau_discipline),
        
        # 5. Supprimer l'ancienne relation entre Cycle et Discipline
        migrations.RemoveField(
            model_name='cycle',
            name='discipline',
        ),
        
        # 6. Modifier le modèle Chapitre pour supporter les deux parents (Palier et Partie)
        migrations.AddField(
            model_name='chapitre',
            name='partie',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='chapitres', 
                to='educalims.partie',
                help_text='Partie associée (optionnel)'
            ),
        ),
        
        migrations.AddField(
            model_name='chapitre',
            name='description',
            field=models.TextField(blank=True, help_text='Description du chapitre'),
        ),
        
        # 7. Créer le nouveau modèle Contenu
        migrations.CreateModel(
            name='Contenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre du contenu', max_length=200)),
                ('fichier', models.FileField(blank=True, help_text='Fichier pédagogique (PDF, vidéo, etc.)', null=True, upload_to='contenus_pedagogiques/')),
                ('type_contenu', models.CharField(
                    choices=[
                        ('pdf', 'PDF'), 
                        ('video', 'Vidéo'), 
                        ('audio', 'Audio'), 
                        ('image', 'Image'), 
                        ('document', 'Document'), 
                        ('autre', 'Autre')
                    ], 
                    default='document', 
                    help_text='Type de contenu', 
                    max_length=50
                )),
                ('description', models.TextField(blank=True, help_text='Description du contenu')),
                ('duree', models.TimeField(blank=True, help_text='Durée estimée (pour vidéos/audios)', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenus', to='educalims.lecon')),
            ],
            options={
                'ordering': ['lecon', 'titre'],
            },
        ),
        
        # 8. Modifier le modèle Leçon
        migrations.AddField(
            model_name='lecon',
            name='objectifs',
            field=models.TextField(blank=True, help_text='Objectifs d\'apprentissage'),
        ),
        
        # 9. Supprimer l'ancien modèle UniteEnseignement
        migrations.DeleteModel(
            name='UniteEnseignement',
        ),
        
        # 10. Rendre le champ discipline obligatoire dans Niveau
        migrations.AlterField(
            model_name='niveau',
            name='discipline',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='niveaux', 
                to='educalims.discipline'
            ),
        ),
        
        # 11. Rendre le champ palier optionnel dans Chapitre
        migrations.AlterField(
            model_name='chapitre',
            name='palier',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='chapitres', 
                to='educalims.palier',
                help_text='Palier associé (optionnel)'
            ),
        ),
        
        # 12. Mettre à jour les contraintes unique_together pour Chapitre
        migrations.AlterUniqueTogether(
            name='chapitre',
            unique_together={('numero', 'titre', 'palier', 'partie')},
        ),
        
        # 13. Mettre à jour les contraintes unique_together pour Niveau
        migrations.AlterUniqueTogether(
            name='niveau',
            unique_together={('nom', 'discipline', 'cycle')},
        ),
    ]
