# Generated by Django 5.2.8 on 2025-11-10 19:31

from django.db import migrations, models
import django.db.models.deletion


def migrate_cycle_discipline(apps, schema_editor):
    """
    Migration des données pour assigner une discipline à chaque cycle
    """
    Cycle = apps.get_model('educalims', 'Cycle')
    Discipline = apps.get_model('educalims', 'Discipline')
    
    # Récupérer tous les cycles sans discipline
    cycles_sans_discipline = Cycle.objects.filter(discipline__isnull=True)
    
    for cycle in cycles_sans_discipline:
        # Assigner la première discipline disponible
        discipline = Discipline.objects.first()
        if discipline:
            cycle.discipline = discipline
            cycle.save()


def reverse_migrate_cycle_discipline(apps, schema_editor):
    """
    Fonction inverse pour la migration
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('educalims', '0006_auto_20251110_1913'),
    ]

    operations = [
        # 1. Ajouter le champ discipline au modèle Cycle (nullable)
        migrations.AddField(
            model_name='cycle',
            name='discipline',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='cycles', 
                to='educalims.discipline'
            ),
        ),
        
        # 2. Migration des données pour assigner une discipline à chaque cycle
        migrations.RunPython(migrate_cycle_discipline, reverse_migrate_cycle_discipline),
        
        # 3. Rendre le champ discipline obligatoire dans Cycle
        migrations.AlterField(
            model_name='cycle',
            name='discipline',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='cycles', 
                to='educalims.discipline'
            ),
        ),
        
        # 4. Ajouter le champ chapitre au modèle Contenu
        migrations.AddField(
            model_name='contenu',
            name='chapitre',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='contenus_directs', 
                to='educalims.chapitre',
                help_text='Chapitre associé (optionnel)'
            ),
        ),
        
        # 5. Rendre le champ lecon optionnel dans Contenu
        migrations.AlterField(
            model_name='contenu',
            name='lecon',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='contenus', 
                to='educalims.lecon',
                help_text='Leçon associée (optionnel)'
            ),
        ),
        
        # 6. Mettre à jour les contraintes unique_together pour Cycle
        migrations.AlterUniqueTogether(
            name='cycle',
            unique_together={('nom', 'discipline')},
        ),
    ]
