# Generated by Django 5.2.8 on 2025-11-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educalims', '0007_auto_20251110_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapitre',
            options={'ordering': ['numero', 'titre']},
        ),
        migrations.AlterModelOptions(
            name='contenu',
            options={'ordering': ['titre'], 'verbose_name_plural': 'Contenus'},
        ),
        migrations.AlterModelOptions(
            name='cycle',
            options={'ordering': ['discipline', 'nom']},
        ),
        migrations.AlterModelOptions(
            name='discipline',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='niveau',
            options={'ordering': ['ordre']},
        ),
        migrations.AddField(
            model_name='niveau',
            name='ordre',
            field=models.PositiveIntegerField(default=1, help_text='Ordre du niveau dans le cycle (ex: 6ème=1, 5ème=2, etc.)'),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='numero',
            field=models.PositiveIntegerField(help_text="Numéro d'ordre du chapitre"),
        ),
        migrations.AlterUniqueTogether(
            name='lecon',
            unique_together={('chapitre', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='palier',
            unique_together={('niveau', 'numero')},
        ),
    ]
