# Generated by Django 5.2.8 on 2025-11-12 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educalims', '0008_add_ordre_to_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenu',
            name='chapitre',
            field=models.ForeignKey(blank=True, help_text='Chapitre associé (optionnel)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contenus_chapitre', to='educalims.chapitre'),
        ),
    ]
