# Generated by Django 5.2.8 on 2025-11-12 19:32

from django.db import migrations


def insert_seconde_stmg(apps, schema_editor):
    """
    Insertion des données pour le niveau Seconde STMG en SVT
    """
    # Importer les modèles via apps pour éviter les imports directs
    Discipline = apps.get_model('educalims', 'Discipline')
    Cycle = apps.get_model('educalims', 'Cycle')
    Niveau = apps.get_model('educalims', 'Niveau')
    Partie = apps.get_model('educalims', 'Partie')
    Chapitre = apps.get_model('educalims', 'Chapitre')

    # 1. Récupérer ou créer la discipline SVT
    svt_discipline, _ = Discipline.objects.get_or_create(
        nom='SVT',
        defaults={'description': 'Sciences de la Vie et de la Terre'}
    )

    # 2. Récupérer ou créer le cycle Lycée
    lycee_cycle, _ = Cycle.objects.get_or_create(
        nom='Lycée',
        defaults={'nom': 'Lycée', 'discipline': svt_discipline, 'description': 'Cycle lycée pour l\'enseignement des SVT'}
    )

    # 3. Récupérer ou créer le niveau Seconde STMG
    seconde_stmg_niveau, _ = Niveau.objects.get_or_create(
        nom='Seconde STMG',
        defaults={
            'nom': 'Seconde STMG',
            'discipline': svt_discipline,
            'cycle': lycee_cycle,
            'ordre': 1,
            'description': 'Classe de Seconde Sciences et Technologies du Management et de la Gestion'
        }
    )

    # 4. Créer les 3 parties du programme
    parties_data = [
        {
            'titre': 'La Terre dans l\'Univers : une planète habitée, la vie et l\'évolution du vivant',
            'description': 'Étude de la Terre comme planète habitée et les mécanismes de l\'évolution du vivant'
        },
        {
            'titre': 'Enjeux planétaires contemporains : énergie, sol',
            'description': 'Analyse des enjeux énergétiques et des ressources en sol à l\'échelle planétaire'
        },
        {
            'titre': 'Corps humain, sport et santé',
            'description': 'Compréhension du fonctionnement du corps humain dans le contexte du sport et de la santé'
        }
    ]

    parties = []
    for i, partie_data in enumerate(parties_data, 1):
        partie, _ = Partie.objects.get_or_create(
            titre=partie_data['titre'],
            niveau=seconde_stmg_niveau,
            defaults={'description': partie_data['description']}
        )
        parties.append(partie)

    # 5. Créer les chapitres pour chaque partie
    
    # Partie 1 - La Terre dans l'Univers
    chapitres_partie1 = [
        {'titre': 'La Terre, une planète habitable', 'numero': 1},
        {'titre': 'Le vivant : nature, unité chimique et structurale', 'numero': 2},
        {'titre': 'Métabolisme, information génétique et environnement', 'numero': 3},
        {'titre': 'Biodiversité et évolution', 'numero': 4}
    ]

    for chapitre_data in chapitres_partie1:
        Chapitre.objects.get_or_create(
            titre=chapitre_data['titre'],
            partie=parties[0],
            defaults={
                'numero': chapitre_data['numero'],
                'description': f'Chapitre {chapitre_data["numero"]} : {chapitre_data["titre"]}'
            }
        )

    # Partie 2 - Enjeux planétaires contemporains
    chapitres_partie2 = [
        {'titre': 'Le soleil, source d\'énergie de la biosphère', 'numero': 5},
        {'titre': 'Les combustibles fossiles', 'numero': 6},
        {'titre': 'Les énergies renouvelables, d\'autres formes d\'énergie solaire', 'numero': 7},
        {'titre': 'Le sol : ressource nécessaire à la survie de l\'humanité', 'numero': 8}
    ]

    for chapitre_data in chapitres_partie2:
        Chapitre.objects.get_or_create(
            titre=chapitre_data['titre'],
            partie=parties[1],
            defaults={
                'numero': chapitre_data['numero'],
                'description': f'Chapitre {chapitre_data["numero"]} : {chapitre_data["titre"]}'
            }
        )

    # Partie 3 - Corps humain, sport et santé
    chapitres_partie3 = [
        {'titre': 'Fonctionnement de l\'organisme et effort physique', 'numero': 9},
        {'titre': 'La pression artérielle', 'numero': 10},
        {'titre': 'Activité physique et santé', 'numero': 11}
    ]

    for chapitre_data in chapitres_partie3:
        Chapitre.objects.get_or_create(
            titre=chapitre_data['titre'],
            partie=parties[2],
            defaults={
                'numero': chapitre_data['numero'],
                'description': f'Chapitre {chapitre_data["numero"]} : {chapitre_data["titre"]}'
            }
        )


def reverse_insert_seconde_stmg(apps, schema_editor):
    """
    Fonction inverse pour supprimer les données insérées
    """
    Niveau = apps.get_model('educalims', 'Niveau')
    Partie = apps.get_model('educalims', 'Partie')
    Chapitre = apps.get_model('educalims', 'Chapitre')

    # Supprimer le niveau Seconde STMG et toutes ses dépendances
    try:
        niveau = Niveau.objects.get(nom='Seconde STMG')
        
        # Supprimer les chapitres associés aux parties de ce niveau
        parties = Partie.objects.filter(niveau=niveau)
        for partie in parties:
            Chapitre.objects.filter(partie=partie).delete()
        
        # Supprimer les parties
        parties.delete()
        
        # Supprimer le niveau
        niveau.delete()
    except Niveau.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('educalims', '0009_fix_contenu_related_name'),
    ]

    operations = [
        migrations.RunPython(insert_seconde_stmg, reverse_insert_seconde_stmg)
    ]
