# Generated by Django 5.2.8 on 2025-11-13 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educalims', '0010_auto_20251112_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEnseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text="Description du type d'enseignement")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='niveau',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Niveau parent (ex: Première pour Première A, B, etc.)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='educalims.niveau'),
        ),
        migrations.AddField(
            model_name='niveau',
            name='type_enseignement',
            field=models.ForeignKey(blank=True, help_text="Type d'enseignement (ex: Enseignement général, Enseignement technique)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='niveaux', to='educalims.typeenseignement'),
        ),
    ]
