# Generated by Django

from django.db import migrations


def create_types_enseignement_and_parent_niveaux(apps, schema_editor):
    """
    Créer les types d'enseignement par défaut et les niveaux parents
    """
    TypeEnseignement = apps.get_model('educalims', 'TypeEnseignement')
    Niveau = apps.get_model('educalims', 'Niveau')
    Discipline = apps.get_model('educalims', 'Discipline')
    Cycle = apps.get_model('educalims', 'Cycle')

    # Créer les types d'enseignement
    enseignement_general, created = TypeEnseignement.objects.get_or_create(
        nom="Enseignement général",
        defaults={'description': 'Enseignement général pour les classes classiques'}
    )

    enseignement_technique, created = TypeEnseignement.objects.get_or_create(
        nom="Enseignement technique",
        defaults={'description': 'Enseignement technique et professionnel'}
    )

    # Utiliser une discipline existante (Mathématiques par exemple)
    try:
        discipline = Discipline.objects.get(nom="Mathématiques")
    except Discipline.DoesNotExist:
        # Si Mathématiques n'existe pas, en créer une nouvelle
        discipline, created = Discipline.objects.get_or_create(
            nom="Éducation",
            defaults={'description': 'Discipline principale pour les niveaux'}
        )

    # Utiliser le cycle Lycée existant
    try:
        cycle = Cycle.objects.get(nom="Lycée", discipline=discipline)
    except Cycle.DoesNotExist:
        # Chercher un cycle Lycée avec n'importe quelle discipline
        cycle = Cycle.objects.filter(nom="Lycée").first()
        if not cycle:
            # Créer un cycle Lycée avec la discipline Mathématiques
            cycle, created = Cycle.objects.get_or_create(
                nom="Lycée",
                discipline=discipline,
                defaults={'description': 'Cycle lycée'}
            )

    # Créer les niveaux parents Première et Terminale
    premiere_parent, created = Niveau.objects.get_or_create(
        nom="Première",
        discipline=discipline,
        cycle=cycle,
        ordre=2,
        defaults={
            'description': 'Niveau parent pour toutes les classes de Première',
            'type_enseignement': enseignement_general,
            'parent': None
        }
    )

    terminale_parent, created = Niveau.objects.get_or_create(
        nom="Terminale",
        discipline=discipline,
        cycle=cycle,
        ordre=3,
        defaults={
            'description': 'Niveau parent pour toutes les classes de Terminale',
            'type_enseignement': enseignement_general,
            'parent': None
        }
    )

    # Mettre à jour les niveaux existants pour leur assigner un type d'enseignement
    # Tous les niveaux existants appartiennent à l'enseignement général par défaut
    Niveau.objects.filter(type_enseignement__isnull=True).update(type_enseignement=enseignement_general)

    # Créer ou mettre à jour la Seconde STMG si elle n'existe pas déjà
    seconde_stmg, created = Niveau.objects.get_or_create(
        nom="Seconde STMG",
        discipline=discipline,
        cycle=cycle,
        ordre=1,
        defaults={
            'description': 'Seconde Sciences et Technologies du Management et de la Gestion',
            'type_enseignement': enseignement_technique,
            'parent': None
        }
    )


def reverse_types_enseignement_and_parent_niveaux(apps, schema_editor):
    """
    Annuler la création des types d'enseignement et niveaux parents
    """
    TypeEnseignement = apps.get_model('educalims', 'TypeEnseignement')
    Niveau = apps.get_model('educalims', 'Niveau')

    # Supprimer les niveaux parents créés
    Niveau.objects.filter(nom__in=['Première', 'Terminale'], parent__isnull=True).delete()

    # Supprimer les types d'enseignement créés
    TypeEnseignement.objects.filter(nom__in=['Enseignement général', 'Enseignement technique']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('educalims', '0011_typeenseignement_niveau_parent_and_more'),
    ]

    operations = [
        migrations.RunPython(
            create_types_enseignement_and_parent_niveaux,
            reverse_types_enseignement_and_parent_niveaux,
        ),
    ]