# Generated by Django

from django.db import migrations


def update_existing_niveaux_hierarchy(apps, schema_editor):
    """
    Mettre à jour les niveaux existants pour leur assigner les bons parents
    """
    Niveau = apps.get_model('educalims', 'Niveau')
    TypeEnseignement = apps.get_model('educalims', 'TypeEnseignement')

    # Récupérer les types d'enseignement
    try:
        enseignement_general = TypeEnseignement.objects.get(nom="Enseignement général")
        enseignement_technique = TypeEnseignement.objects.get(nom="Enseignement technique")
    except TypeEnseignement.DoesNotExist:
        print("Types d'enseignement non trouvés, création annulée")
        return

    # Récupérer les niveaux parents
    premiere_parent = Niveau.objects.filter(nom="Première", parent__isnull=True).first()
    terminale_parent = Niveau.objects.filter(nom="Terminale", parent__isnull=True).first()

    if not premiere_parent or not terminale_parent:
        print("Niveaux parents non trouvés, mise à jour annulée")
        return

    # Mapping des niveaux enfants vers leurs parents
    niveau_mappings = {
        # Classes de Première
        'Première A': premiere_parent,
        'Première B': premiere_parent,
        'Première S': premiere_parent,

        # Classes de Terminale
        'Terminale A': terminale_parent,
        'Terminale B': terminale_parent,
        'Terminale C': terminale_parent,
        'Terminale D': terminale_parent,
    }

    # Mettre à jour les niveaux existants
    updated_count = 0
    for niveau_nom, parent in niveau_mappings.items():
        niveaux = Niveau.objects.filter(nom=niveau_nom, parent__isnull=True)
        for niveau in niveaux:
            niveau.parent = parent
            niveau.type_enseignement = enseignement_general
            niveau.save()
            updated_count += 1
            print(f"  - {niveau_nom} rattaché à {parent.nom}")

    # Mettre à jour la Seconde STMG pour qu'elle appartienne à l'enseignement technique
    seconde_stmg = Niveau.objects.filter(nom__icontains="STMG", parent__isnull=True).first()
    if seconde_stmg:
        seconde_stmg.type_enseignement = enseignement_technique
        seconde_stmg.save()
        updated_count += 1
        print(f"  - {seconde_stmg.nom} assignée à l'enseignement technique")

    # Tous les autres niveaux (collège) appartiennent à l'enseignement général
    other_levels = Niveau.objects.filter(
        parent__isnull=True,
        type_enseignement__isnull=True
    ).exclude(nom__in=['Première', 'Terminale'])

    for niveau in other_levels:
        niveau.type_enseignement = enseignement_general
        niveau.save()
        updated_count += 1
        print(f"  - {niveau.nom} assigné à l'enseignement général")

    print(f"Total de {updated_count} niveaux mis à jour")


def reverse_update_existing_niveaux_hierarchy(apps, schema_editor):
    """
    Annuler les modifications de hiérarchie
    """
    Niveau = apps.get_model('educalims', 'Niveau')

    # Supprimer les relations parent pour les niveaux enfants
    child_levels = Niveau.objects.filter(
        nom__in=[
            'Première A', 'Première B', 'Première S',
            'Terminale A', 'Terminale B', 'Terminale C', 'Terminale D'
        ]
    )

    for niveau in child_levels:
        niveau.parent = None
        niveau.type_enseignement = None
        niveau.save()


class Migration(migrations.Migration):

    dependencies = [
        ('educalims', '0012_insert_default_data'),
    ]

    operations = [
        migrations.RunPython(
            update_existing_niveaux_hierarchy,
            reverse_update_existing_niveaux_hierarchy,
        ),
    ]