# Generated by Django 5.2.8 on 2025-11-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educalims', '0013_update_existing_niveaux_hierarchy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenu',
            name='chapitre',
        ),
        migrations.RemoveField(
            model_name='contenu',
            name='lecon',
        ),
        migrations.AddField(
            model_name='contenu',
            name='cahier_type_lycee',
            field=models.FileField(blank=True, help_text='Cahier type pour le lycée (PDF, DOC, HTML)', null=True, upload_to='lycee/cahiers_types/'),
        ),
        migrations.AddField(
            model_name='contenu',
            name='categorie_niveau',
            field=models.CharField(choices=[('college', 'Collège'), ('lycee', 'Lycée'), ('commun', 'Commun aux deux')], default='commun', help_text='Catégorie du contenu selon le niveau', max_length=20),
        ),
        migrations.AddField(
            model_name='contenu',
            name='chapitres',
            field=models.ManyToManyField(blank=True, help_text='Chapitre(s) associé(s) au contenu', related_name='contenus_chapitre', to='educalims.chapitre'),
        ),
        migrations.AddField(
            model_name='contenu',
            name='fiche_college',
            field=models.FileField(blank=True, help_text='Fiche pédagogique pour le collège (PDF, DOC, HTML)', null=True, upload_to='college/fiches/'),
        ),
        migrations.AddField(
            model_name='contenu',
            name='fiche_lycee',
            field=models.FileField(blank=True, help_text='Fiche pédagogique pour le lycée (PDF, DOC, HTML)', null=True, upload_to='lycee/fiches/'),
        ),
        migrations.AddField(
            model_name='contenu',
            name='lecons',
            field=models.ManyToManyField(blank=True, help_text='Leçon(s) associée(s) au contenu', related_name='contenus', to='educalims.lecon'),
        ),
        migrations.AddField(
            model_name='contenu',
            name='sujet_college',
            field=models.FileField(blank=True, help_text="Sujet d'exercice pour le collège (PDF, DOC, HTML)", null=True, upload_to='college/sujets/'),
        ),
        migrations.AddField(
            model_name='contenu',
            name='sujet_lycee',
            field=models.FileField(blank=True, help_text="Sujet d'exercice pour le lycée (PDF, DOC, HTML)", null=True, upload_to='lycee/sujets/'),
        ),
        migrations.AlterField(
            model_name='contenu',
            name='fichier',
            field=models.FileField(blank=True, help_text='Fichier pédagogique général (PDF, vidéo, etc.)', null=True, upload_to='contenus_pedagogiques/'),
        ),
        migrations.AlterField(
            model_name='contenu',
            name='type_contenu',
            field=models.CharField(choices=[('pdf', 'PDF'), ('video', 'Vidéo'), ('audio', 'Audio'), ('image', 'Image'), ('document', 'Document'), ('texte', 'Fichier texte'), ('html', 'Fichier HTML'), ('word', 'Document Word'), ('fiche_college', 'Fiche Collège'), ('sujet_college', 'Sujet Collège'), ('fiche_lycee', 'Fiche Lycée'), ('cahier_type', 'Cahier Type'), ('sujet_lycee', 'Sujet Lycée'), ('autre', 'Autre')], default='document', help_text='Type de contenu principal', max_length=50),
        ),
    ]
