# Generated by Django 5.2.8 on 2025-11-14 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educalims', '0014_remove_contenu_chapitre_remove_contenu_lecon_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contenu',
        ),
    ]
