# Generated by Django 5.2.8 on 2025-11-14 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educalims', '0015_delete_contenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre du contenu', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description du contenu')),
                ('type_contenu', models.CharField(choices=[('fiche', 'Fiche'), ('cahier_type', 'Cahier Type'), ('sujet', 'Sujet')], help_text='Type de contenu', max_length=20)),
                ('fichier', models.FileField(help_text='Fichier pédagogique (PDF, DOC, HTML, etc.)', upload_to='contenus/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('chapitre', models.ForeignKey(blank=True, help_text='Chapitre associé (collège et lycée)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contenus_chapitre', to='educalims.chapitre')),
                ('discipline', models.ForeignKey(help_text='Discipline du contenu', on_delete=django.db.models.deletion.CASCADE, to='educalims.discipline')),
                ('lecon', models.ForeignKey(blank=True, help_text='Leçon associée (uniquement pour le collège)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contenus_lecon', to='educalims.lecon')),
                ('niveau', models.ForeignKey(help_text='Niveau du contenu', on_delete=django.db.models.deletion.CASCADE, to='educalims.niveau')),
            ],
            options={
                'verbose_name_plural': 'Contenus',
                'ordering': ['discipline', 'niveau', 'type_contenu', 'titre'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('chapitre__isnull', False), ('lecon__isnull', True)), models.Q(('chapitre__isnull', True), ('lecon__isnull', False)), models.Q(('chapitre__isnull', False), ('lecon__isnull', False)), _connector='OR'), name='lecon_or_chapitre_not_both')],
            },
        ),
    ]
