# Generated by Django 5.2.8 on 2025-11-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educalims', '0016_contenu'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contenu',
            name='lecon_or_chapitre_not_both',
        ),
        migrations.AddConstraint(
            model_name='contenu',
            constraint=models.CheckConstraint(condition=models.Q(('lecon__isnull', False), ('chapitre__isnull', False), _connector='OR'), name='lecon_or_chapitre_required'),
        ),
    ]
