# Generated by Django 5.2.8 on 2025-11-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educalims', '0017_remove_contenu_lecon_or_chapitre_not_both_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contenu',
            name='lecon_or_chapitre_required',
        ),
        migrations.RemoveField(
            model_name='contenu',
            name='chapitre',
        ),
        migrations.RemoveField(
            model_name='contenu',
            name='lecon',
        ),
        migrations.AddField(
            model_name='contenu',
            name='chapitres',
            field=models.ManyToManyField(blank=True, help_text='Chapitre(s) associé(s) au contenu (collège et lycée)', related_name='contenus_chapitres', to='educalims.chapitre'),
        ),
        migrations.AddField(
            model_name='contenu',
            name='lecons',
            field=models.ManyToManyField(blank=True, help_text='Leçon(s) associée(s) au contenu (collège)', related_name='contenus_lecons', to='educalims.lecon'),
        ),
    ]
