# Generated by Django 5.2.8 on 2025-11-15 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educalims', '0018_remove_contenu_lecon_or_chapitre_required_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenuTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre du contenu', max_length=200)),
                ('fichier', models.FileField(help_text='Fichier pédagogique (PDF, DOC, HTML, etc.)', upload_to='contenus_test/')),
                ('description', models.TextField(blank=True, help_text='Description du contenu')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('chapitre', models.ForeignKey(help_text='Chapitre associé au contenu', on_delete=django.db.models.deletion.CASCADE, related_name='contenus_test', to='educalims.chapitre')),
            ],
            options={
                'verbose_name': 'Contenu Test',
                'verbose_name_plural': 'Contenus Test',
                'ordering': ['chapitre', 'titre'],
            },
        ),
    ]
