# Generated by Django 5.2.8 on 2025-11-15 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educalims', '0019_contenutest'),
    ]

    operations = [
        # Supprimer les anciennes tables Contenu et ContenuTest
        migrations.DeleteModel('ContenuTest', ),
        migrations.DeleteModel('Contenu', ),

        # Recréer le nouveau modèle Contenu simplifié
        migrations.CreateModel(
            name='Contenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre du contenu', max_length=200)),
                ('fichier', models.FileField(help_text='Fichier pédagogique (PDF, DOC, HTML, etc.)', upload_to='contenus/')),
                ('description', models.TextField(blank=True, help_text='Description du contenu')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('chapitre', models.ForeignKey(blank=True, help_text='Chapitre associé au contenu', null=True, on_delete=models.CASCADE, related_name='contenus', to='educalims.chapitre')),
            ],
            options={
                'verbose_name': 'Contenu',
                'verbose_name_plural': 'Contenus',
                'ordering': ['chapitre', 'titre'],
            },
        ),
    ]
